### ISSUE TITLE
Transactions involving both users data and other app data.

### ISSUE THREAD

**Issue by fisx** [agrafix/users#24]
If I am not mistaken, the backend packages want me to create a two database connection pools pointing into two unconnected databases: one for users, and one for the rest of the app data.  This raises at least two questions:

1. we need to keep track of additional, app-specific user data, so we manage a users table in the app database as well.  now every user has two IDs, one pointing into the app-manage user table and one pointing in the database managed by the users package(s).  is there a better way?
1. how can I implement transactions spanning both data managed by the users package and data managed by my app?

We've come up with this at our company:

```haskell
newtype DB a = ...  -- (some transformer stack containing a reader to `SqlBackend`)

runUsersCmd :: (Users.Persistent -> IO a) -> DB a
runUsersCmd cmd = liftDB . ReaderT $ \(sqlBackend :: SqlBackend) ->
  liftIO $ cmd (Users.Persistent (`runReaderT` sqlBackend))
```

This essentially lets you call the users interface from inside our own app monad.  We are happy with this, but it's less than obvious, and I was wondering what your thoughts are on this solution.  What would be an ideal solution, and what would be required for these packages to allow for that solution?

Thanks!

**Comment by agrafix** [comment]
This is not correct, the backend packages work with existing connections/connection pools. As long as you the other tables in your database namewise do not conflict with `users`' tables, you can use one single database.

Thus:

1. To keep track of additional app-specific data, we recommend creating a foreign key to the login row. For the `persistent` backend we explicitly export the `LoginId` for this purpose. 

2. This depends on the backend, for the `postgresql-simple` backend no modifications are needed, you can simple wrap any sequence of calls to `users` and your own database tables with [withTransaction](http://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple.html#v:withTransaction). For `persistent` I don't think this is possible with the current API. This could be fixed by adding a second associated type to the `UserStorageBackend` which indicated in which monad the actions should run. Then, you could make all the `persistent` backend actions run in the `SqlPersistT IO a` which is equivialent to a transaction if I recall correctly. Let me know if you want to work on this and need help.

**Comment by fisx** [comment]
This is helpful, thanks!

I think now that (a) the solution I've suggested above is the right one for our code-base and (b) the reason our code is so complicated is that transaction management in persist is not very sophisticated.  That's enough for me to move on.

thanks again~
